# Generated by Django 4.1.1 on 2023-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite_app', '0002_alter_person_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(max_length=100),
        ),
    ]
