# Generated by Django 4.1.1 on 2023-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite_app', '0003_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
