# Generated by Django 4.1.1 on 2023-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite_app', '0004_alter_person_age_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
    ]
