# Generated by Django 4.1.1 on 2023-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ernakulam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branchid', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('hours', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kollam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branchid', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('hours', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kottayam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branchid', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('hours', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thrissur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branchid', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('hours', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trivandrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branchid', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('hours', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
    ]
